zuul:
  ignored-services: '*'
  routes:
    codePipeline:
      path: /application/**
      serviceId: app1
    eureka:
      path: /dashboard/**
      url: http://discovery:8761/
  prefix: /application
  sensitive-headers: Cookie,Set-Cookiels
security:
  basic:
    enabled: false

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000